### ISSUE TITLE
fsf.org: FSF Associate Forum

### ISSUE THREAD

**Issue by davidhedlund** [davidhedlund/Feedback-for-websites#10]
**This issue has been reported to sysadmin@fsf.org (I've archived the response form [gnu.org #1199231] FSF Associate Forum).**

https://www.fsf.org/associate/forum/ can be found on either
* The top menu at fsf.org have this link: [Members forum](https://www.fsf.org/associate/about-the-members-forum). That page have this link: [Members — enter the forum!](https://www.fsf.org/associate/forum/).
* Google Search: [FSF Associate Forum](https://encrypted.google.com/search?hl=en&q=FSF%20Associate%20Forum).

However, https://www.fsf.org/associate/forum/ cannot be accessed by people with FSF Associate Accounts:

> ### The page isn’t redirecting properly
> [Abrowser / IceCat / Tor Browser / Firefox / Firefox ESR] has detected that the server is redirecting the request for this address in a way that will never complete.
> * This problem can sometimes be caused by disabling or refusing to accept cookies.

Non-Firefox browsers GNOME Web, and Midori, can not enter the forum either.

The FSF admins didn't fix this issue.

**Comment by davidhedlund** [comment]
https://github.com/davidhedlund/WILB/issues/18

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
Still down according to a FSF member.

**Comment by ian-kelling** [comment]
I just tested and it is working for me on firefox 52.0-1, and gnu icecat 45.7.0.

**Comment by ian-kelling** [comment]
I also just tested in safe mode and with a fresh profile in both browsers. also working

**Comment by davidhedlund** [comment]
@ian-kelling Thank you.
