### ISSUE TITLE
mozdev.org/bugs/: Insecure Connection

### ISSUE THREAD

**Issue by davidhedlund** [davidhedlund/Feedback-for-websites#12]
HTTPS Everywhere 5.2.13 is not compatible with mozdev.org/bugs/

>### Your connection is not secure
>
>The owner of www.mozdev.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
>
>www.mozdev.org uses an invalid security certificate.
>The certificate expired on 2016-09-11 19:39. The current time is 2017-04-04 07:14.
>Error code: SEC_ERROR_EXPIRED_CERTIFICATE

David Boswell <davidwboswell@yahoo.com> (the owner of the mozdev.org domain name) responded:
> There isn't currently anyone actively involved in managing the mozdev.org site.  If that is something you would be interested in helping with, I'll be happy to connect you with other people who have also expressed interest in running the site.

**Comment by stanlane** [comment]
They have updated their certificate now.

**Comment by davidhedlund** [comment]
They have updated their certificate now.
